# Generated by Django 3.2.15 on 2022-11-28 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active', models.BooleanField(default=False)),
                ('Text', models.CharField(max_length=10000)),
                ('Optionone', models.CharField(blank=True, max_length=1000)),
                ('Optiononecount', models.IntegerField(default=0)),
                ('Optiontwo', models.CharField(blank=True, max_length=1000)),
                ('Optiontwocount', models.IntegerField(default=0)),
                ('Optionthree', models.CharField(blank=True, max_length=1000)),
                ('Optionthreecount', models.IntegerField(default=0)),
                ('Optionfour', models.CharField(blank=True, max_length=1000)),
                ('Optionfourcount', models.IntegerField(default=0)),
                ('Optionfive', models.CharField(blank=True, max_length=1000)),
                ('Optionfivecount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.URLField(default='')),
                ('facebook', models.URLField(default='')),
                ('discord', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=10000)),
                ('creator', models.IntegerField(default=None)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=None, max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('digits', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=None)),
                ('Active', models.BooleanField(default=False)),
                ('Text', models.CharField(max_length=10000)),
                ('Optionone', models.CharField(max_length=1000)),
                ('Optiononecount', models.IntegerField(default=0)),
                ('Optiontwo', models.CharField(max_length=1000)),
                ('Optiontwocount', models.IntegerField(default=0)),
                ('Optionthree', models.CharField(blank=True, max_length=1000)),
                ('Optionthreecount', models.IntegerField(default=0)),
                ('Optionfour', models.CharField(blank=True, max_length=1000)),
                ('Optionfourcount', models.IntegerField(default=0)),
                ('Optionfive', models.CharField(blank=True, max_length=1000)),
                ('Optionfivecount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_inf',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.TextField(max_length=100)),
                ('career', models.TextField(max_length=100)),
                ('bio', models.TextField(max_length=1000)),
                ('DP', models.CharField(max_length=10000000)),
                ('CP', models.CharField(max_length=10000000)),
                ('annexes', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.community')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.contact')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.survey')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.history')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.payment')),
            ],
        ),
    ]
