# Generated by Django 3.2.15 on 2022-11-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publishing_Fetching', '0002_auto_20221130_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inf',
            name='CP',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='Community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.community'),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='Contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.contact'),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='DP',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='Survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.survey'),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='annexes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='career',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='country',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.history'),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.payment'),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
