# Generated by Django 3.2.15 on 2022-12-07 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Publishing_Fetching', '0003_auto_20221130_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.SlugField()),
                ('Title', models.CharField(max_length=50)),
                ('Thumbnail', models.CharField(max_length=500)),
                ('Concept', models.TextField(max_length=10000)),
                ('Content', models.TextField(max_length=100000)),
                ('Rating', models.IntegerField(blank=True, default=0)),
                ('Berries', models.IntegerField(blank=True, default=0)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('restriction', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.user_inf')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(max_length=10000)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.user_inf')),
            ],
        ),
    ]
