# Generated by Django 3.2.15 on 2022-12-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publishing_Fetching', '0006_user_inf_auths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_inf',
            name='auths',
        ),
    ]
