# Generated by Django 3.2.15 on 2022-12-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publishing_Fetching', '0008_auto_20221208_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_inf',
            name='user',
        ),
    ]
