# Generated by Django 3.2.15 on 2022-12-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publishing_Fetching', '0010_auto_20221208_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('pdc1_name', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('pdc1_img', models.CharField(blank=True, default='', max_length=100000, null=True)),
                ('pdc1_link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='Desc',
            field=models.TextField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Links',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publishing_Fetching.affiliate'),
        ),
    ]
