# Generated by Django 3.2.15 on 2022-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publishing_Fetching', '0011_auto_20221208_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Desc',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Links',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
