export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_UPDATE = "AUTH_UPDATE"
export const AUTH_JWT = "AUTH_JWT"

export const AUTH_CHECK ="AUTH_CHECK"


export const FETCH_SUCCESS = "FETCH_SUCCESS"


export const FETCH_FAIL = "FETCH_FAIL"
export const SELECTSUCCESS = "SELECTSUCCESS"


export const FONT_SELECT = "FONT_SELECT"

export const INSERT_SELECT = "INSERT_SELECT"

export const DELETE_SELECT = "DELETE_SELECT"


export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL"
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS"

export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL"
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS"



export const SubmitBar_Display = "SubmitBar_Display"


