# Generated by Django 4.2.3 on 2023-07-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('country', models.TextField(blank=True, max_length=100, null=True)),
                ('career', models.TextField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('DP', models.CharField(blank=True, max_length=10000000, null=True)),
                ('CP', models.CharField(blank=True, max_length=10000000, null=True)),
                ('annexes', models.IntegerField(blank=True, default=0, null=True)),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('JWT_per', models.CharField(blank=True, max_length=10000, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
