# Generated by Django 4.2.3 on 2023-07-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FetchSubmit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='sno',
            new_name='id',
        ),
    ]
